### ISSUE TITLE
Error while creating modules/user with multiple trusted entities

### ISSUE THREAD

**Issue by orisgarno** [traveloka/terraform-aws-iam-role#19]
### Summary
Unable to create IAM User role with multiple trusted entities.

### Error
Error: module.srs_sqs.module.role_sqs_reader.data.aws_iam_policy_document.with_mfa: statement.0.principals.0.identifiers: should be a list

Error: module.srs_sqs.module.role_sqs_reader.data.aws_iam_policy_document.without_mfa: statement.0.principals.0.identifiers: should be a list

### Step to repro

```
module "role_sqs_reader" {
  source = "github.com/traveloka/terraform-aws-iam-role.git//modules/user?ref=v0.6.0"

  role_name                  = "${module.role_sqs_reader_name.name}"
  role_path                  = "/"
  role_description           = "Allow instance to read sqs and s3"
  role_force_detach_policies = true
  role_max_session_duration  = 43200

  trusted_users = [
    "${local.consumer_arn}"
  ]

  mfa_required = false
}
locals{
  consumer_arn                           = [
    "arn:aws:iam::517530806209:root", // Migration only
    "${data.terraform_remote_state.srsssch_app.app_instance_profile_arn}"
  ]
}
```

### Resolution
Update from 
```
    principals = {
      type        = "AWS"
      identifiers = "${var.trusted_users}"
    }
```
to
```
    principals = {
      type        = "AWS"
      identifiers = ["${var.trusted_users}"]
    }
```
Tested on my local computer by changing the module under .terraform/.modules dir.

**Comment by nin9swells** [comment]
Hello,
I can't reproduce this. I'm using
Terraform v0.11.10
+ provider.aws v1.60.0

Anyway, it seems you want to create cross account role, I'm currently addressing it on #21
