### ISSUE TITLE
Empty string role path will throw an error

### ISSUE THREAD

**Issue by nin9swells** [traveloka/terraform-aws-iam-role#24]
This module will throw an error if empty string is passed to `role_path`. This is caused by the module trying to substring an empty string.

Workaround, instead of putting empty string, put `/`

**Comment by rafikurnia** [comment]
Hi @nin9swells 
I believe that is part of constraints from AWS IAM API for [creating role](https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateRole.html) that for path ***the string must begin and end with forward slashes***. Therefore, it is not our module's bug. 

That is also the reason why the default value set is "/":
https://github.com/traveloka/terraform-aws-iam-role/blob/5d14b7e96bff1e5f83b3f0b20c598536a323288a/variables.tf#L12-L16
